Repository keironchaudhry/women-in-tech-hackathon, pull requests merged in 2023-03, with the labels that each got.

#1 First PR: Add temporary "pull request and branch" instructions to readme
  README.md
  documentation/PR and branch instructions/branch label.png
  documentation/PR and branch instructions/merge pull request button.png
  documentation/PR and branch instructions/new pull request.png
  documentation/PR and branch instructions/pull request count.png
  documentation/PR and branch instructions/pull request message.png
  documentation/PR and branch instructions/reviewers.png
Labels: documentation

#11 Set up flask app, connect API and prepare for deployment
  Procfile
  app.py
  requirements.txt
  templates/base.html
  templates/home.html
Labels: backend

#12 Add env file to gitignore
  .gitignore
Labels: enhancement, backend

#15 Wesley: Frontend design
  .vscode/settings.json
  assets/imgs/ada.jpg
  assets/imgs/ailogo.jpg
  assets/imgs/female-simbol.jpg
  assets/imgs/grace.jpg
  assets/imgs/katherine.jpg
  index.html
  style.css
Labels: frontend

#14 Update the app and template to process message history
  app.py
  templates/home.html
Labels: backend

#16 Remove vscode settings from repo
  .gitignore
  .vscode/MAINTAINERS.md
  .vscode/arctictern.py
  .vscode/client.cnf
  .vscode/font_fix.py
  .vscode/heroku_config.sh
  .vscode/init_tasks.sh
  .vscode/launch.json
  .vscode/make_url.py
  .vscode/mysql.cnf
  .vscode/rmdep.sh
  .vscode/settings.json
  .vscode/start_mysql.sh
  .vscode/upgrades.json
  .vscode/uptime.sh
  .vscode/version.txt
Labels: backend

#20 made a bunch of adjustments to make the page responsive in all screen
  index.html
  style.css
Labels: enhancement, frontend

#24 Important: Moved navbar + footer components into base.html + css files
  index.html
  static/style.css
  style.css
  templates/base.html
Labels: enhancement, frontend

#26 Added wireframes to the documentation
  documentation/Wireframes/Dashboard Selection.png
  documentation/Wireframes/Dashboard chat.jpg
  documentation/Wireframes/Description.png
  documentation/Wireframes/Main page_.png
  documentation/Wireframes/uiux.png
Labels: documentation

#27 Move index.html content into home.html template + change footer position
  static/style.css
  templates/home.html
Labels: enhancement, frontend

#28 Delete index.html page
  index.html
Labels: duplicate, frontend

#29 navbar
  static/navbar.js
  static/style.css
  templates/base.html
  templates/home.html
Labels: frontend

#30 Charley
  README.md
Labels: documentation

#31 fixed the about section imgs and the footer styling
  static/assets/imgs/ada.jpg
  static/assets/imgs/ada_lovelace.jpg
  static/assets/imgs/ailogo.jpg
  static/assets/imgs/female-simbol.jpg
  static/assets/imgs/grace-hopper.jpg
  static/assets/imgs/grace.jpg
  static/assets/imgs/katherine-johnson.jpg
  static/assets/imgs/katherine.jpg
  static/navbar.js
  static/style.css
  templates/home.html
Labels: frontend

#35 Add favicon files/links
  assets/icons/about.txt
  assets/icons/android-chrome-192x192.png
  assets/icons/android-chrome-512x512.png
  assets/icons/apple-touch-icon.png
  assets/icons/favicon-16x16.png
  assets/icons/favicon-32x32.png
  assets/icons/favicon.ico
  assets/icons/site.webmanifest
  templates/base.html
Labels: enhancement, frontend

#36 Created, and added style to the selection html page.
  static/assets/card_imgs/ada.jpg
  static/assets/card_imgs/grace.jpg
  static/assets/card_imgs/katherine.jpg
  static/style.css
  templates/selection.html
Labels: frontend

#37 Replace redirect system with asynchronous API calls
  app.py
  static/chat.js
  templates/chat.html
Labels: backend

#38 Add selection route
  app.py
Labels: backend

#39 Fix navbar display bugs
  templates/base.html
  templates/home.html
Labels: bug, frontend

#40 Amengemechu/build biographies page 23
  assets/icons/ada_lovelace.jpg
  assets/icons/grace-hopper.jpg
  assets/icons/katherine-johnson.jpg
  static/assets/imgs/ada-lovelace.jpg
  static/style.css
  templates/home.html
Labels: enhancement, frontend

#41 Remove now obsolete chat API from bottom of home page
  templates/home.html
Labels: frontend

#42 Fix: Move favicon files into static + render
  static/assets/favicon/apple-touch-icon.png
  static/assets/favicon/favicon-16x16.png
  static/assets/favicon/favicon-32x32.png
  static/assets/favicon/favicon.ico
  templates/base.html
Labels: bug, frontend

#43 Top of home page: mobile screen media query
  static/style.css
  templates/home.html
Labels: frontend

#47 Charley
  .gitignore
  README.md
  static/assets/imgs/grace-hopper.jpg
  static/assets/imgs/katherine-johnson.jpg
  static/style.css
  templates/home.html
Labels: enhancement, frontend

#45 updated the main section to be more responsive
  static/assets/card_imgs/ailogo.svg
  static/assets/card_imgs/female-symbol.svg
  static/assets/imgs/ailogo.jpg
  static/assets/imgs/female-simbol.jpg
  static/style.css
  templates/home.html
Labels: frontend

#48 Fix: amend Flask template language across hrefs/buttons/links in home page
  templates/base.html
  templates/home.html
Labels: enhancement, frontend

#49 Readme commit: Addition of TOC, organsation and development of content
  README.md
  documentation/wireframes.md
Labels: documentation

#50 Chat page improvements and various fixes
  app.py
  static/chat.js
  static/script.js
  static/style.css
  templates/base.html
  templates/chat.html
Labels: enhancement, backend, frontend

#54 Finish chat functionality and add responsive layouts
  app.py
  static/chat.js
  static/style.css
  templates/chat.html
Labels: backend, frontend

#55 few fixes to the CSS/Design
  static/style.css
  templates/base.html
  templates/home.html
Labels: frontend

#56 Charley
  README.md
  documentation/screenshots/ChatWIT-amiresponsive.png
Labels: documentation

#57 Add chat page responsive styles
  static/style.css
Labels: bug, frontend

#58 Add missing styles
  static/style.css
Labels: bug, frontend

#59 Small adjustments to the Home page
  static/style.css
  templates/base.html
  templates/home.html
Labels: enhancement, frontend

#60 updated wireframes imgs and added a colours img
  documentation/Wireframes/Colours.jpg
  documentation/Wireframes/Dashboard Selection.png
  documentation/Wireframes/Dashboard chat.jpg
  documentation/Wireframes/Description.png
  documentation/Wireframes/Main page_.png
Labels: documentation

#61 Updated the read.md, wireframes.md and h3 styling
  README.md
  documentation/wireframes.md
  static/style.css
Labels: documentation

#62 Add selection page functionality
  static/chat.js
  static/style.css
  templates/base.html
  templates/chat.html
  templates/home.html
  templates/selection.html
Labels: enhancement, frontend

#63 Fix navbar bugs
  static/style.css
  templates/base.html
  templates/home.html
Labels: bug, frontend

#64 Add spacing and buttons to bios
  templates/home.html
Labels: enhancement, frontend

#66 added a few user stories target audience and home page img credits
  README.md
Labels: documentation

#69 Readme commit: Modify and add user stories, plus various changes arou…
  README.md
Labels: documentation

#68 Updated the bios btn and selection page hover effect
  static/style.css
  templates/home.html
Labels: enhancement, frontend

#70 API call updates
  app.py
  static/chat.js
Labels: bug, backend

#71 Fixed the card class hovering issue
  static/style.css
  templates/selection.html
Labels: bug, frontend

#72 Set chat nav link to active on selection page
  templates/base.html
Labels: bug, frontend

#73 Readme commit: Features
  README.md
  documentation/features/ai convo sample 1.png
  documentation/features/ai convo sample 2.png
  documentation/features/ai convo sample 3.png
  documentation/features/asset loader.png
  documentation/features/biographies 1.png
  documentation/features/chat page side bar.png
  documentation/features/chat with women in tech history.png
  documentation/features/footer.png
  documentation/features/hero image.png
  documentation/features/nabar 2.png
  documentation/features/navbar small.png
  documentation/features/navbar.png
  documentation/features/selections page.png
Labels: documentation

#74 Readme commit: Lighthouse testing
  README.md
  documentation/lighthouse/lighthouse chat page desktop.png
  documentation/lighthouse/lighthouse chat page mobile.png
  documentation/lighthouse/lighthouse home page desktop.png
  documentation/lighthouse/lighthouse home page mobile.png
  documentation/lighthouse/lighthouse selection page desktop.png
  documentation/lighthouse/lighthouse selection page mobile.png
Labels: documentation

#76 Readme commit: Manual testing of user stories
  README.md
Labels: documentation

#77 a few minor spelling/grammar edits to the readme
  README.md
Labels: documentation
